import 'package:prokit_flutter/main/utils/AppConstant.dart';

const NBSplashImage = 'images/newsBlog/nb_splash_image.png';
const NBWalkThroughImage1 = '$BaseUrl/images/newsBlog/nb_walk1.jpg';
const NBWalkThroughImage2 = '$BaseUrl/images/newsBlog/nb_walk2.jpg';
const NBFacebookLogo = 'images/newsBlog/nb_facebook_image.png';
const NBGoogleLogo = 'images/newsBlog/nb_google_image.png';
const NBProfileImage = 'images/newsBlog/nb_profile.jpeg';
const NBNewsImage1 = 'images/newsBlog/nb_newsImage1.jpg';
const NBNewsImage2 = 'images/newsBlog/nb_newsImage2.jpg';
const NBNewsImage3 = '$BaseUrl/images/newsBlog/nb_newsImage3.jpg';
const NBSportSNews1 = 'images/newsBlog/nb_sportsImage1.jpg';
const NBSportSNews2 = '$BaseUrl/images/newsBlog/nb_sportsImage2.jpg';
const NBTechNews1 = '$BaseUrl/images/newsBlog/nb_technologyImage1.jpg';
const NBTechNews2 = '$BaseUrl/images/newsBlog/nb_technologyImage2.jpg';
const NBRefreshIcon = 'images/newsBlog/nb_refresh_icon.png';
const NBRefreshNextIcon = 'images/newsBlog/nb_refreshNext_icon.png';
const NBChineseFlag = 'images/newsBlog/nb_chineseFlag.png';
const NBEnglishFlag = 'images/newsBlog/nb_english.png';
const NBFrenchFlag = 'images/newsBlog/nb_french.png';
const NBMelayuFlag = 'images/newsBlog/nb_melayu.png';
const NBSpainFlag = 'images/newsBlog/nb_spain.png';
const NBTechnologyCategory = '$BaseUrl/images/newsBlog/nb_technologyCategory.jpg';
const NBFashionCategory = 'images/newsBlog/nb_fashionCategory.jpg';
const NBSportsCategory = '$BaseUrl/images/newsBlog/nb_sportsCategory.jpg';
const NBScienceCategory = '$BaseUrl/images/newsBlog/nb_scienceCategory.jpg';
